spring:
  # Spring JMS Settings
  datasource:
    validationQuery: SELECT 1
    #Remove abandoned connection,So, new connection will be created and made available to threads which are waiting for DB connection
    removeAbandoned: true
    #If any connection is not used for 120 seconds, consider that connection as "abandoned"
    removeAbandonedTimeout: 120
    #Log the stack trace of abandoned connection
    logAbandoned: true
    # Maximum number of active connections that can be allocated from this pool at the same time.
    #The maximum number of active connections that can be allocated from this pool at the same time. The default value is 100
    maxActive: 50
    # The maximum number of connections that should be kept in the pool at all times
    maxIdle: 10
    # Number of ms to wait before throwing an exception if no connection is available.
    #The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception. Default value is 30000 (30 seconds)
    maxWait: 10000
    # Validate the connection before borrowing it from the pool.
    testOnBorrow: true
    #The indication of whether objects will be validated when a connection is first created. If an object fails to validate, it will be throw SQLException. Default value is false
    testOnConnect: true
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    # For detailed document https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    generate-ddl: false
    hibernate:
      #none, validate, save, create, create-drop
      #use create-drop to enable import.sql file import
      ddl-auto: update
      connection.CharSet: utf8
      connection.characterEncoding: utf8
      connection.useUnicode: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_versioned_data: true
      org.hibernate.envers.audit_table_suffix: _history
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
